object Versions {
    const val appCompat = "1.5.0"
    const val core = "1.8.0"
    const val coroutines = "1.6.4"
    const val hilt = "2.38.1"
    const val junit = "4.13.2"
    const val junitKtx = "1.1.3"
    const val kotlin = "1.7.10"
    const val lifeCycle = "2.5.1"
    const val material = "1.6.1"
    const val okhttp = "4.9.1"
    const val retrofit = "2.9.0"
    const val recyclerView = "1.2.1"
    const val room = "2.4.3"
    const val espresso = "3.4.0"
    const val glide = "4.13.2"
}
